### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by dmcgoldrick** [dmcgoldrick/HTSmetadata#1]
User was trying the code and ran into an encoding error:

Traceback (most recent call last):
  File "metadataFromHTSfileOfFiles.py", line 271, in <module>
    main()
  File "metadataFromHTSfileOfFiles.py", line 243, in main
    result=metadataFromHTSfileOfFiles(f,Group=l)
  File "metadataFromHTSfileOfFiles.py", line 193, in metadataFromHTSfileOfFiles
    for path in paths:
  File "/usr/local/Anaconda/envs/py3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

should add more documentation on the -i format and a test to the archive

**Comment by dmcgoldrick** [comment]
don't put .bai or binary files in the -i input file
